development:
  type: server_db
  url: http://localhost:7474

test:
  type: server_db
  url: http://localhost:7575

production: &production
  type: server_db
  url: <%= ENV["GRAPHENEDB_URL"] %>

staging:
  <<: *production
