default: &default
  omniauth_provider_key: <%= ENV["OMNIAUTH_PROVIDER_KEY"] %>
  omniauth_provider_secret: <%= ENV["OMNIAUTH_PROVIDER_SECRET"] %>
  jwt_secret_key_base: <%= ENV["JWT_SECRET_KEY_BASE"] %>

development:
  <<: *default
  secret_key_base: 149d9913eef52d662f0dede91cadb10c99522095e22334540463c421b0fc005d5854de7582fc0961c4ddcf0261de22de7aa6c61d7a2ac679e14af17cb7cfd28f

test:
  <<: *default
  secret_key_base: 97e90176c84cd5e760571f40df4aaaf3fdc5afac206afdae15830e1ae66a02e8468239037aecccbc7c03fe031aa81d6b82cce0d5eaf9e6c11a7c2e048e764406
  omniauth_provider_key: "OMNIAUTH_PROVIDER_KEY"
  omniauth_provider_secret: "OMNIAUTH_PROVIDER_SECRET"
  jwt_secret_key_base: "JWT_SECRET_KEY_BASE"

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
